replicaCount: 3
image:
  repository: asdumitrescu/andrei
  tag: "1.16"
app:
  name: weatherapp
  port: 5000
  envVar: "Production"  # Assuming this is the variable value for 'ENVIRONMENT'
service:
  type: NodePort
  port: 30010
  nodePort: 30000
  targetPort: 5000

