replicaCount: 3
image:
  repository: asdumitrescu/weather-app
  tag: "button-left-menu"
app:
  name: weatherapp
  port: 5000
service:
  type: ClusterIP
  port: 30010
  targetPort: 5000
ingress:
  enabled: true
