replicaCount: 3
image:
  repository: asdumitrescu/weather-app
  tag: "button-left-menu"
app:
  name: weatherapp
  port: 5000
service:
  type: LoadBalancer
  port: 30010
  nodePort: 30000
  targetPort: 5000
