apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}  # Dynamically set the namespace
  labels:
    app: {{ .Values.app.name }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  # Specifies an Application Load Balancer
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      
  selector:
    app: {{ .Values.app.name }}

